### PR TITLE
Warnings as errors fixes

### PR DESCRIPTION
**Pull request by al-tu**
fixing some warnings, most are minor ones, except for missing copy constructor for Pose6D which leads to the following message (compiled with -std=c++2a):
`warning: implicitly-declared 'octomath::Pose6D::Pose6D(const octomath::Pose6D&)' is deprecated [-Wdeprecated-copy]`
`note: because 'octomath::Pose6D' has user-provided 'octomath::Pose6D& octomath::Pose6D::operator=(const octomath::Pose6D&)'`
so i've added copy ctor for consistency
notes:
it might make sense to provide move operations along with copy, conditionaly defined if c++ >= 11  is available
i've also added warning as errors flags to compiler flags list - don't know if it's appropriate for this project, so i'm ok to remove it if requested
unused parameters names wrapped with comments - might be removed alternatively, seems like a style choice that should be consistent with the whole project (is it now?)

### CODE REVIEW

**Comment by ahornung** [comment]
Thanks, merged!

**Comment by wxmerkt** [comment]
@ahornung Could you please create a patch release for v1.9 with this PR included? I'd love to get the version in Noetic updated :-).

**Comment by ahornung** [comment]
@wxmerkt Done, thanks for the heads up!

**Comment by wxmerkt** [comment]
Thank you, the release is out - https://github.com/ros/rosdistro/pull/28068

**Pull request merged**
