### PR TITLE
Merge devel into ros2 branch

### PR DESCRIPTION
**Pull request by ruffsl**
Looks like the ros2 branch is lagging a bit behind devel. I've just resolved the merge conflict between the cmake version bumps in ros2 and the qt5 package.xml depends from devel. It doesn't look like ament is being used, so I'm not sure why these are two different branches to begin with, given that `ament_target_dependencies` still doesn't seem to work with this package and headers must be manually included for downstream packages.

Related: https://github.com/ros-planning/geometric_shapes/pull/154

cc @mikaelarguedas

### CODE REVIEW

**Comment by wxmerkt** [comment]
I have a slightly different proposition I'd love your feedback on.

I'd like to propose to retire the `ros2` branch entirely and amend the `package.xml` to support both ROS1 and ROS2 using package format 3 conditions. This is purely a CMake project and I don't see a reason why we need to maintain a separate branch. The only difference between OctoMap for ROS1 & ROS2 is the change from `catkin` to `ament` which can be made conditional.

(When we started the `ros2` branch, I wasn't aware of the `condition="$ROS_VERSION == 1"` option for the package format so we could fix that now and only maintain `devel`.)

 What are your thoughts @ruffsl @mikaelarguedas?

**Comment by ruffsl** [comment]
I like the idea of consolidated code base. Are there example package elsewhere in ecosystem we could mimic? I have no idea about mixing catkin with ament via logic switching.

**Comment by wxmerkt** [comment]
I think this PR is a good example: https://github.com/ethz-adrl/ifopt/pull/52

**Comment by mikaelarguedas** [comment]
Yes this sounds like a good plan :+1:
It can get tricky (needing quite some conditionals) if catkin or ament macros are used in the CMakeLists. It doesnt seem to be the case here so this should work fine.

One thing for e.g. rosdep is that ROS 2 looks only for packages that are registered in the ament index and not "all places that have a package.xml". So there may be something to tweak there (this issue has some information about it https://github.com/ros-infrastructure/rosdep/issues/724)

**Comment by wxmerkt** [comment]
@ruffsl Can we close this PR now that `devel` supports ROS2 / the `ros2` branch is deprecated?

**Pull request closed without merging**
