### PR TITLE
Alternative rendering

### PR DESCRIPTION
**Pull request by felixendres**
See the commit message for a detailed description.

The following screenshots show the exact effect on CPU, RAM (see the output of "top" on the upper left) and FPS (shown within the octovis window on the upper left, below "File" in Hz) on my machine (using Intel Corporation Broadwell-U Integrated Graphics). I would guess that the effect would be even more pronounced with better graphics cards, as the rendering bottleneck is moved from the CPU to the GPU.

Regular rendering
octovis-16-regular

Rendering with the new method of this pull request
octovis-16-alternate

### CODE REVIEW

**Comment by felixendres** [comment]
Similar screenshots as above, but with a smaller octree (same as above but cutoff at 15)
Regular:
octovis-15-regular
Alternate:
octovis-15-alternate

**Comment by felixendres** [comment]
P.S.: If you want to see the difference on your machine, FPS can be easily displayed by adding `setFPSIsDisplayed(true);` to the end of the constructor in _octovis/src/ViewerWidget.cpp_

**Comment by ahornung** [comment]
Cool, thanks for the PR! Somehow this also includes the commits from #122, which I already merged so it's now in a conflicted state.

Would you mind rebasing and/or sending a new PR?

**Comment by felixendres** [comment]
Weird. I didn't manage to create a PR from just the last commit, so in the end I deleted and recreated my github fork, then merged the changes in manually :-1: 
The new PR is #139

**Pull request closed without merging**
