### PR TITLE
Fix broken octovis-config.cmake

### PR DESCRIPTION
**Pull request by chhtz**
This fixes https://github.com/OctoMap/octomap/issues/129
I don't know if the `QGLViewer` variables are required at all. "It works for me"

### CODE REVIEW

**Comment by ahornung** [comment]
I think they are required when there is no system-wide installation of QGLViewer available and the source version in octovis is used. 

You can easily test by removing libqglviewer and reconfiguring with CMake (probably the CMakeCache needs to be deleted manually).

**Comment by chhtz** [comment]
I tried that, (using the devel-branch) I'm still getting this line in the installed octovis-config.cmake:
```
set_and_check(OCTOVIS_LIBRARY_DIRS "" "${PACKAGE_PREFIX_DIR}/lib")
```

**Comment by ahornung** [comment]
Are you sure that you built completely clean? (remove liqglviewer packages, remove build directory, re-run cmake and make)

For me they are set in both the installed and non-installed (source tree) octovis-config.cmake:

```
set(OCTOVIS_LIBRARIES
  "/home/armin/code/octomap/octovis/src/extern/QGLViewer/libQGLViewer.so"
  "optimized;/usr/lib/x86_64-linux-gnu/libQtOpenGL.so;debug;/usr/lib/x86_64-linux-gnu/libQtOpenGL.so;optimized;/usr/lib/x86_64-linux-gnu/libQtGui.so;debug;/usr/lib/x86_64-linux-gnu/libQtGui.so;optimized;/usr/lib/x86_64-linux-gnu/libQtXml.so;debug;/usr/lib/x86_64-linux-gnu/libQtXml.so;optimized;/usr/lib/x86_64-linux-gnu/libQtCore.so;debug;/usr/lib/x86_64-linux-gnu/libQtCore.so"
  "/home/armin/code/octomap/lib/liboctovis.so"
)

```

**Comment by chhtz** [comment]
Yes, this is approximately what I get. As I said in #129 this is broken, because `set_and_check` fails when an empty string is passed as second argument (and the third argument is completely ignored).
An alternative to hide the problem would be to just switch the order of `"@QGLViewer_LIBRARY_DIR@"` and `"@PACKAGE_OCTOVIS_LIB_DIR@"` (the `QGLViewer...` arguments would silently be ignored in that case). Maybe just using `set` instead of `set_and_check` is better. Or `set_and_check only the `PACKAGE_OCTOVIS...` variables and manually append the `QGLViewer...` arguments afterwards.

I'm not really a cmake expert, so no idea what the best way is ...

**Comment by ahornung** [comment]
See comment in #129, closing here.

**Pull request closed without merging**
